/**
 * Voice + topic templates for forum seed data, sliced by language.
 *
 * Three lang buckets:
 *   - en : English (formal corporate, Slack-y, ESL, technical, casual)
 *   - zh : Chinese (Traditional + Simplified mixed; one bucket because both
 *          surface on /zh/discussions and feel like one community)
 *   - ja : Japanese (formal keigo + casual)
 *
 * The seed script picks (product, lang) pool then samples a voice + topic +
 * padding all from the same pool, so a post is internally consistent.
 *
 * Diversity contract:
 *   - 8-15 voice archetypes per (product, lang)
 *   - 15-30 topic templates per (product, lang)
 *   - Distinct titles enforced via Set in the seed script
 */

// ============================================================
// Slot vocabulary — picked randomly when expanding templates.
// Slots are language-agnostic (brand names, technical terms).
// ============================================================

export const SLOTS = {
  cloud: {
    site:        ['Shopee', 'Ruten', 'Salesforce', 'HubSpot', 'a Korean vendor portal', 'our SAP', 'Notion', 'Monday.com', 'Pipedrive', 'Stripe dashboard', 'Quickbooks Online', 'Xero', 'PChome 24h', '蝦皮賣家中心', '玉山銀行 ATM 系統', 'GitHub Actions logs', 'YouTube Studio', 'TikTok Ads Manager', 'Meta Business Suite', '楽天市場の管理画面', 'メルカリ Shops', 'freee 会計'],
    flow:        ['login', 'invoice download', 'order export', 'lead enrichment', 'price scrape', 'CSV upload', 'multi-tab batch', 'OCR + paste', 'PDF parse', 'data sync', 'form filling'],
    err:         ['element not found', '"selector returned null"', 'Playwright timeout 30s', 'CAPTCHA loop', '2FA prompt I cannot pass', 'session expired mid-run', 'iframe never loads', 'too many redirects', 'modal blocking next click', 'rate-limited (429)', 'browser crashed', 'memory blew past 4GB'],
    module:      ['browser.click', 'browser.fill', 'browser.scrape', 'sheets.append', 'csv.read', 'pdf.extract', 'http.batch', 'llm.extract', 'flow.if', 'flow.foreach', 'flow.retry', 'storage.put', 'image.crop', 'compare.diff'],
    file:        ['orders-2026-04.csv', 'invoices_q1.zip', 'leads.xlsx', 'screenshot-fail.png', 'log-2026-04-29.txt', 'config.yaml'],
    feature:     ['variable scoping', 'multi-step undo', 'visual regression diff', 'mobile viewport recording', 'PDF table extraction', 'WhatsApp module', 'LINE module', 'sub-workflow reuse', 'parallel branches', 'retry with backoff', 'human-approval gate', 'workflow templates marketplace', 'screenshot diffing', 'time-travel debugging'],
    person:      ['my boss', '老闆', '財務妹妹', 'the CFO', 'our intern', '一個業務', 'a customer', 'the data team', '上司', '経理担当'],
    timing:      ['daily', 'every Monday morning', '每月底', 'on demand', 'when an order comes in', 'before standup', '毎晩', '月次で'],
  },
  code: {
    repo:        ['flyto-engine', 'flyto-cloud', 'flyto-core', 'a 200k-LOC Rails monolith', 'our internal SDK', 'a NestJS service', 'a Spring Boot microservice', 'flyto-vscode', 'a Go gateway', 'a React Native app', 'an Electron desktop app', 'our Phoenix backend'],
    finding:     ['a CVE in lodash 4.17.20', 'taint flow from req.body to db.query', 'an exposed API key', 'GPL contamination via transitive dep', 'an unauthenticated /admin endpoint', 'a missing CSRF check', 'SSRF in image proxy', 'open redirect on /go', 'XXE in xml parser', 'a deprecated TLS 1.0 listener', 'reflected XSS via search param', 'insecure deserialization', 'IDOR on /orders/{id}', 'race in payment confirm'],
    rule:        ['flyto-core/sast/sql-injection', 'flyto-indexer/secret/aws-key', 'flyto-indexer/license/agpl', 'flyto-engine/cspm/s3-public', 'custom rule .flyto-rules.yaml grep_deny'],
    score:       ['A', 'B', 'C-', 'D', 'F', '67/100', '720'],
    ci:          ['GitHub Actions', 'GitLab CI', 'Jenkins', 'Buildkite', 'CircleCI', 'Drone', 'Bitbucket Pipelines', 'Azure DevOps'],
    ide:         ['VSCode', 'Cursor', 'JetBrains Fleet', 'IntelliJ IDEA', 'WebStorm', 'GoLand', 'PyCharm', 'Vim', 'Neovim', 'Helix', 'Zed', 'Sublime'],
    sdlc:        ['pre-commit', 'CI', 'staging deploy', 'production', 'PR review', 'release branch'],
    standard:    ['SOC 2', 'ISO 27001', 'PCI DSS', 'HIPAA', 'GDPR', 'NIS2', 'TSC CC6.1'],
    tool:        ['Snyk', 'Aikido', 'Mend', 'Dependabot', 'Trivy', 'Semgrep', 'CodeQL', 'Checkmarx', 'Veracode', 'SonarCloud', 'BlackDuck'],
    language:    ['TypeScript', 'Python', 'Go', 'Rust', 'Java', 'Ruby', 'PHP', 'Kotlin', 'C#', 'Swift', 'Elixir', 'Scala'],
  },
};

// ============================================================
// Voice archetypes per (product, lang).
// Each voice = { id, prefix[], length }
// length: 'micro' | 'short' | 'medium' | 'long'
// ============================================================

export const VOICES = {
  cloud: {
    en: [
      { id: 'newbie',        prefix: ['Hi all,', 'Hello,', 'Sorry — newbie question.', 'Just installed,'], length: 'medium' },
      { id: 'frustrated',    prefix: ['Why does this never work…', 'Genuinely losing my mind.', 'Two days on this.'], length: 'medium' },
      { id: 'concise',       prefix: [''], length: 'short'  },
      { id: 'rambling',      prefix: ['So, context:', 'Long one — bear with me.'], length: 'long' },
      { id: 'corporate',     prefix: ['Hi Flyto2 team,', 'Evaluating Flyto2 for our team.', 'Procurement question:'], length: 'medium' },
      { id: 'casual',        prefix: ['yo', 'hey', 'wassup', 'quick one —'], length: 'short' },
      { id: 'sales_eval',    prefix: ['Comparing tools right now.', 'Evaluating Flyto2 vs Zapier — '], length: 'medium' },
      { id: 'angry',         prefix: ['THIS IS UNACCEPTABLE.', 'Already wasted 2 hours.', 'Frankly, this is broken.'], length: 'short' },
      { id: 'polite_old',    prefix: ['Greetings,', 'Dear support team,', 'To whom it may concern,'], length: 'medium' },
      { id: 'curious',       prefix: ['Random thought —', 'Curious if anyone else…', 'Maybe a dumb question:'], length: 'short' },
      { id: 'showcase',      prefix: ['Just shipped a workflow for our team.', 'Built this last weekend, sharing in case it helps.'], length: 'long' },
      { id: 'feature_req',   prefix: ['Would love to see…', 'Feature request:', 'Wishlist:'], length: 'medium' },
      { id: 'bug_repro',     prefix: ['## Repro steps', 'Steps to reproduce:', 'Bug:'], length: 'long' },
      { id: 'one_liner',     prefix: [''], length: 'micro' },
      { id: 'thinking',      prefix: ['hmm', 'ok so', '...'], length: 'short' },
      { id: 'broken_en',     prefix: ['hello sir,', 'please help me,', 'i am sorry for my english,'], length: 'short' },
      { id: 'philosophical', prefix: ['Been thinking about automation lately.', 'Open question to the community —'], length: 'long' },
      { id: 'panic',         prefix: ['URGENT — production down', 'Help, deadline in 2 hours'], length: 'medium' },
      { id: 'docs_complain', prefix: ['Docs say X but…', 'The docs are unclear on'], length: 'medium' },
      { id: 'comparison',    prefix: ['vs Make.com:', 'compared with n8n,'], length: 'medium' },
      { id: 'designer',      prefix: ['Small UX nit —', 'Tiny design feedback:'], length: 'short' },
      { id: 'late_night',    prefix: ['3am here, just hit a wall.', "It's late, brain fried."], length: 'short' },
      { id: 'follow_up',     prefix: ['Following up on my last post —', 'Bumping this:'], length: 'short' },
      { id: 'gratitude',     prefix: ['Just wanted to say —', 'Quick win to share:'], length: 'short' },
    ],
    zh: [
      { id: 'tw_polite',     prefix: ['想請問一下,', '不好意思,', '請教各位前輩,', '想跟大家請教,'], length: 'medium' },
      { id: 'tw_corporate',  prefix: ['您好,本公司正在評估 Flyto2。', '敬啟者,', '想諮詢一下,'], length: 'medium' },
      { id: 'tw_panic',      prefix: ['糟糕,我搞壞了什麼?', '緊急 — production 出事了,', '凌晨三點半,我可能眼花了'], length: 'short' },
      { id: 'tw_casual',     prefix: ['哈囉大家好,', '好久沒發文了,', '隨手問一下,'], length: 'short' },
      { id: 'tw_grumble',    prefix: ['為什麼這麼麻煩,', '怎麼跑都不順,', '官方文件這邊好像沒寫到'], length: 'medium' },
      { id: 'tw_showcase',   prefix: ['分享一下我做的東西。', '記錄一下昨天的 workflow,', '寫一個 case study 給大家參考'], length: 'long' },
      { id: 'tw_feature_req',prefix: ['希望能加上', '建議加個', '能不能新增'], length: 'medium' },
      { id: 'tw_meta',       prefix: ['關於 Flyto2 這個專案,', '想問個 high-level 的問題:', '純粹好奇:'], length: 'short' },
      { id: 'tw_bug',        prefix: ['Bug 回報:', '重現步驟:', '我在 macOS 14.4 上遇到'], length: 'medium' },
      { id: 'tw_late_night', prefix: ['凌晨還在跟它纏鬥,', '半夜貼一下卡關的點,'], length: 'short' },
      { id: 'cn_simple',     prefix: ['请问一下,', '咨询个问题。', '想了解一下,', '请教大家,'], length: 'medium' },
    ],
    ja: [
      { id: 'jp_keigo',      prefix: ['お世話になっております。', 'いつも利用させていただいております。'], length: 'medium' },
      { id: 'jp_question',   prefix: ['質問ですが、', 'ちょっと困っています。', '初心者なので恐縮ですが、'], length: 'medium' },
      { id: 'jp_casual',     prefix: ['こんにちは。', 'ちょっと聞きたいんですが、', 'すみません、'], length: 'short' },
      { id: 'jp_bug',        prefix: ['バグ報告:', '再現手順:', '気になる挙動:'], length: 'medium' },
      { id: 'jp_feature',    prefix: ['機能要望:', 'こうなれば嬉しい:', 'できれば追加してほしい:'], length: 'medium' },
      { id: 'jp_share',      prefix: ['共有です。', '備忘:', '社内で使ってみました。'], length: 'short' },
    ],
  },
  code: {
    en: [
      { id: 'security_eng',  prefix: ['Security question:', 'For our threat model:', 'Triage question:'], length: 'medium' },
      { id: 'cto',           prefix: ['Considering Warroom for our org.', 'Evaluating to replace Snyk.'], length: 'long' },
      { id: 'redteamer',     prefix: ['Pentest question:', 'Red-team scenario:'], length: 'medium' },
      { id: 'devops',        prefix: ['CI integration —', 'In our pipeline,', 'Pipeline gotcha:'], length: 'medium' },
      { id: 'compliance',    prefix: ['Auditor is asking about', 'For SOC 2 evidence,'], length: 'medium' },
      { id: 'developer',     prefix: ['My PR got blocked —', 'Why does scanner flag', 'Can someone explain why'], length: 'medium' },
      { id: 'oss_curious',   prefix: ['Reading the source —', 'Browsing the indexer code,'], length: 'short' },
      { id: 'enterprise',    prefix: ['Procurement question:', 'For Enterprise pricing:'], length: 'medium' },
      { id: 'comparison',    prefix: ['vs Aikido:', 'Compared to Snyk,', 'How is this different from CodeQL?'], length: 'medium' },
      { id: 'integrator',    prefix: ['Trying to integrate with', 'API question:'], length: 'medium' },
      { id: 'researcher',    prefix: ['Curious about the methodology behind', 'How do you approach'], length: 'medium' },
      { id: 'feature_req',   prefix: ['Feature request:', 'Would love support for'], length: 'medium' },
      { id: 'bug_report',    prefix: ['Bug:', '## Repro', 'Possible bug —'], length: 'long' },
      { id: 'panicked',      prefix: ['Urgent — possible breach', 'Critical CVE just dropped:'], length: 'medium' },
      { id: 'meta_q',        prefix: ['About the closed-loop:', 'About the product itself:'], length: 'short' },
      { id: 'self_host',     prefix: ['Self-host scenario:', 'Air-gapped install:'], length: 'medium' },
      { id: 'noise',         prefix: ['Too many false positives in', 'This rule keeps firing on'], length: 'medium' },
      { id: 'thanks',        prefix: ['Just caught a real one —', 'Real win to share:'], length: 'short' },
      { id: 'docs_q',        prefix: ['Docs say…', 'Where in the docs do I find'], length: 'short' },
      { id: 'cli_q',         prefix: ['$ flyto-index ', 'CLI question —', 'When I run'], length: 'short' },
    ],
    zh: [
      { id: 'tw_sec',        prefix: ['想請教一下,', '安全部門在問:', '紅隊週會剛好提到:'], length: 'medium' },
      { id: 'tw_cto',        prefix: ['正在評估 Warroom 取代 Snyk。', '想問 CTO 級別的問題:'], length: 'long' },
      { id: 'tw_devops',     prefix: ['CI 整合的問題,', '我們是 GitLab,', '想接到 pipeline 的話'], length: 'medium' },
      { id: 'tw_dev',        prefix: ['為什麼我的 PR 被擋?', '這個 rule 是不是有點 aggressive?', '可以解釋一下'], length: 'medium' },
      { id: 'tw_feature',    prefix: ['希望可以支援', '建議加上', '能不能在 dashboard 看'], length: 'medium' },
      { id: 'tw_compare',    prefix: ['跟 Snyk 比', '和 Aikido 差在哪', 'CodeQL 跟這個怎麼選'], length: 'medium' },
      { id: 'tw_bug',        prefix: ['誤判回報:', 'Bug:', '掃描漏掉了'], length: 'medium' },
      { id: 'tw_panic',      prefix: ['緊急 — 客戶通報', '剛收到 CVE 通知,', '客戶 audit 後天:'], length: 'medium' },
      { id: 'cn_simple',     prefix: ['请问一下,', '咨询个问题:', '想了解'], length: 'medium' },
    ],
    ja: [
      { id: 'jp_keigo',      prefix: ['お世話になっております。', 'いつも利用させていただいております。'], length: 'medium' },
      { id: 'jp_security',   prefix: ['セキュリティチームから質問:', '監査の関係で、', '社内ポリシー上'], length: 'medium' },
      { id: 'jp_dev',        prefix: ['PR がブロックされました:', 'スキャナーが flag しました:', '質問ですが、'], length: 'medium' },
      { id: 'jp_compare',    prefix: ['Snyk と比較して、', 'CodeQL からの移行を検討:'], length: 'medium' },
      { id: 'jp_bug',        prefix: ['誤検知の報告:', 'バグかも:', '再現手順:'], length: 'medium' },
      { id: 'jp_feature',    prefix: ['機能要望:', '対応してほしい:'], length: 'medium' },
    ],
  },
};

// ============================================================
// Topic templates per (product, lang).
// Each = { cat, t } where cat ∈ question|bug|feature|discussion
// ============================================================

export const TOPICS = {
  cloud: {
    en: [
      { cat: 'question', t: 'How do I {flow} on {site}? The selector keeps failing.' },
      { cat: 'question', t: 'Best way to handle {err} when running {flow}?' },
      { cat: 'question', t: 'Can {module} accept a CSV with {file}?' },
      { cat: 'question', t: 'Does Flyto2 support {feature} yet?' },
      { cat: 'question', t: 'Trying to scrape {site} {timing} — any patterns I should follow?' },
      { cat: 'question', t: 'How do I share a workflow with {person} who is not a dev?' },
      { cat: 'question', t: 'Pricing question: how do compute points work for {flow}?' },
      { cat: 'question', t: 'Headless mode — what is the perf vs headed for {flow}?' },
      { cat: 'question', t: 'Why does {module} need permission to access {file}?' },
      { cat: 'question', t: 'How granular can workflow permissions get? Need {person} read-only.' },
      { cat: 'question', t: 'Self-hosted — does the scheduler need a public IP or just outbound?' },
      { cat: 'question', t: 'API documented for {module}? Want to call it from our backend.' },
      { cat: 'question', t: 'How do I retry only the failed step without rerunning the whole flow?' },
      { cat: 'question', t: 'Mobile viewport recording is choppy — known issue or my setup?' },
      { cat: 'question', t: 'Image upload to {site}: which Flyto2 module supports drag-drop?' },
      { cat: 'question', t: "What's the rate-limit policy when scraping {site} aggressively?" },
      { cat: 'bug',      t: 'Bug: {flow} on {site} fails with {err} on macOS 14.4.' },
      { cat: 'bug',      t: '{module} returns empty array even though I see data in DOM.' },
      { cat: 'bug',      t: 'Recorder freezes when I open {site} — repro 100%.' },
      { cat: 'bug',      t: 'Workflow runs fine local, fails on hosted scheduler with {err}.' },
      { cat: 'bug',      t: 'Variables vanish between sub-workflows when using {module}.' },
      { cat: 'bug',      t: 'Modal capture: clicks register but {err} fires after.' },
      { cat: 'bug',      t: 'When the page has an iframe + shadow DOM, {module} cannot find the input.' },
      { cat: 'bug',      t: 'CAPTCHA detection blocks {flow} on {site}. Pause + manual works but is awful.' },
      { cat: 'bug',      t: 'Date-picker on {site} renders weirdly with timezone offsets.' },
      { cat: 'bug',      t: 'On {site}, the Cloudflare challenge always re-prompts even though cookie is set.' },
      { cat: 'feature',  t: 'Please add {feature} — would unblock our {flow}.' },
      { cat: 'feature',  t: 'Idea: official module for {site}. Right now I cobble it from {module}.' },
      { cat: 'feature',  t: 'Can {feature} be exposed on the CLI? Cron-only access right now.' },
      { cat: 'feature',  t: 'Integration with {site} would 10x our team output.' },
      { cat: 'feature',  t: 'Built-in OCR module for invoice headers in {file}?' },
      { cat: 'feature',  t: 'Add a "show what changed" diff view between two workflow versions.' },
      { cat: 'feature',  t: 'Sub-workflow versioning so I can pin to a stable child without breaking parents.' },
      { cat: 'feature',  t: 'Webhook trigger for {site} change-detection. Currently polling every 5 min.' },
      { cat: 'discussion', t: 'How are folks handling {err} on slow corporate VPNs?' },
      { cat: 'discussion', t: 'What is your favourite Flyto2 recipe? Mine is the {flow} pipeline I run {timing}.' },
      { cat: 'discussion', t: 'Anyone migrating off Zapier? Tips before I commit?' },
      { cat: 'discussion', t: 'Privacy paranoia — does {module} actually run on my machine or phone home?' },
      { cat: 'discussion', t: 'Hot take: visual editors + Markdown export = best of both worlds.' },
      { cat: 'discussion', t: 'My team runs Flyto2 nightly for {flow}. Sharing the gotchas we hit.' },
      { cat: 'discussion', t: 'PSA: keep your Chromium pinned — auto-updates broke our {flow} last week.' },
      { cat: 'discussion', t: 'Cleanest pattern for credentials? .env vs Flyto2 secret store?' },
      // ---- expanded variety ----
      { cat: 'question', t: 'Does Flyto2 store the recorded video, or only the structured workflow?' },
      { cat: 'question', t: 'Cron syntax — does Flyto2 use UTC or local timezone for {timing} schedules?' },
      { cat: 'question', t: 'How do I detect when {site} returns an empty result vs a real error?' },
      { cat: 'question', t: 'Best practice for waiting on a slow modal that loads data over WebSocket?' },
      { cat: 'question', t: "What's the safest way to store OAuth tokens for {site} that expire every 24h?" },
      { cat: 'question', t: 'Multi-account login on {site} — how do you switch identities mid-flow?' },
      { cat: 'question', t: 'Fingerprinting: does {site} block headless? Workarounds beyond user-agent spoof?' },
      { cat: 'question', t: 'Recursive directory scrape on {site} — pattern for bounded-depth crawl?' },
      { cat: 'question', t: 'How big can a {file} be before {module} starts dropping rows?' },
      { cat: 'question', t: 'Webhook signature verification example for incoming triggers?' },
      { cat: 'bug',      t: 'Memory leak: 4-hour run on {site} hits 6GB RSS, killed by OOM.' },
      { cat: 'bug',      t: 'Time of day matters — {flow} works at 9am, fails at 11pm. Same {site}.' },
      { cat: 'bug',      t: 'Race condition: two parallel branches modify same variable, last write wins randomly.' },
      { cat: 'bug',      t: 'Workflow exports work locally, import on Linux fails with "invalid magic bytes".' },
      { cat: 'bug',      t: '{module} ignores `--verbose`. No way to see what it actually does.' },
      { cat: 'bug',      t: 'Edge case: empty {file} crashes {module} instead of returning empty array.' },
      { cat: 'bug',      t: 'Recorder loses focus when DevTools opens. Must close DevTools to continue.' },
      { cat: 'feature',  t: 'Could `flow.foreach` accept a stream so we don\'t buffer 100k rows in memory?' },
      { cat: 'feature',  t: 'Conditional breakpoints in the recorder — pause only when value matches.' },
      { cat: 'feature',  t: 'Diff between two run logs to find why one succeeded and the other did not.' },
      { cat: 'feature',  t: 'Native module for Telegram (we coordinate via Telegram, not Slack).' },
      { cat: 'feature',  t: 'Per-step timeout instead of per-workflow.' },
      { cat: 'feature',  t: 'Accept a video file as input for OCR + transcript pipelines.' },
      { cat: 'discussion', t: "Anyone else feel like recorders are the future and Selenium is dead? Curious if I'm just biased." },
      { cat: 'discussion', t: 'We replaced 18 internal scripts with 6 Flyto2 workflows. AMA.' },
      { cat: 'discussion', t: 'Workflow file as code review artefact — has anyone built a github action that posts diffs?' },
      { cat: 'discussion', t: 'Counter-take: visual editors hide complexity until it bites. JSON-first?' },
      { cat: 'discussion', t: 'How are accountants and ops folks reacting when you onboard them to Flyto2?' },
      { cat: 'discussion', t: 'Story time: Flyto2 saved us from migrating off our 12-year-old ERP.' },
      { cat: 'discussion', t: 'Open source debate — what would convince you to upstream a private module?' },
      { cat: 'question', t: '{flow} works in dev but the scheduled run misses the modal. What changed?' },
      { cat: 'question', t: 'Custom JS step inside a workflow — recommended for one-off transforms?' },
      { cat: 'question', t: 'GDPR cleanup — does Flyto2 keep any user-data trace after a workflow finishes?' },
      { cat: 'question', t: 'Comparing run history: how do I see which step is the slowest over 100 runs?' },
    ],
    zh: [
      { cat: 'question', t: '想請教,把 {site} 的資料抓回 {file} 應該怎麼處理會比較穩定?' },
      { cat: 'question', t: '我用 {module} 想做 {flow},結果 {err},是不是漏設定了?' },
      { cat: 'question', t: 'Variables 跨 sub-workflow 的時候會不會被覆蓋?{flow} 跑完一輪資料就消失。' },
      { cat: 'question', t: '加個 {feature} 請問有規劃嗎?跟 {site} 對接可以省掉很多步驟。' },
      { cat: 'question', t: 'API 文件裡的 {module} 沒有給範例,有人實際跑過嗎?' },
      { cat: 'question', t: '怎麼把 {file} 的內容批次塞進 {site}?目前是手動貼。' },
      { cat: 'question', t: 'Self-host 的話,Docker image 在哪邊抓比較新?' },
      { cat: 'question', t: '請教各位,{flow} 跑到一半被 {err} 中斷,用 retry 也救不了,該怎麼處理?' },
      { cat: 'question', t: '我們公司資安部門問:{module} 跑時憑證會送到哪?' },
      { cat: 'question', t: '想學 Flyto2,有推薦的學習路徑嗎?' },
      { cat: 'bug',      t: '在 {timing} 跑 {flow} 會偶發 {err},rerun 就好,有解嗎?' },
      { cat: 'bug',      t: '{module} 卡在 loading 動畫,DevTools 看 network 一直在等 — wait_for 也救不了。' },
      { cat: 'bug',      t: '錄製器在 {site} 開啟會 freeze,Mac M2 環境下 100% 重現。' },
      { cat: 'bug',      t: 'Modal 把 {flow} 卡住,點擊有反應但下一步不執行。' },
      { cat: 'bug',      t: 'Sub-workflow 跑完,parent 的 variable 不見了。' },
      { cat: 'bug',      t: '在 {site} 抓資料,有 iframe 就抓不到。' },
      { cat: 'bug',      t: 'Hosted scheduler 跑 {flow} 失敗,本地 OK。' },
      { cat: 'feature',  t: '希望可以新增 {site} 的官方 module,目前是用 {module} 拼的。' },
      { cat: 'feature',  t: '建議加 LINE module,我們很多客戶都在 LINE 上。' },
      { cat: 'feature',  t: '能不能新增 {feature}?跟我們公司 {flow} 高度相關。' },
      { cat: 'feature',  t: '希望 CLI 可以支援 {feature}。' },
      { cat: 'discussion', t: '大家都怎麼讓 {person} 用 Flyto2?有沒有減少教學的訣竅?' },
      { cat: 'discussion', t: '我們公司在思考要把 {flow} 從外包改成自己用 Flyto2 做,有人做過比較嗎?' },
      { cat: 'discussion', t: '隱私問題:{module} 真的不會把資料送出去嗎?' },
      { cat: 'discussion', t: '分享一下:{flow} 我們改用 Flyto2 後省了 80% 時間。' },
      { cat: 'discussion', t: '想討論一下,Flyto2 跟 Power Automate 各有什麼適合的場景?' },
      // ---- expanded variety ----
      { cat: 'question', t: '{flow} 跑兩小時記憶體吃到 5GB,有人遇過類似問題嗎?' },
      { cat: 'question', t: '時區問題:cron 表達式是用 UTC 還是台北時間?' },
      { cat: 'question', t: 'OAuth token 過期 24h 一次,Flyto2 怎麼自動 refresh?' },
      { cat: 'question', t: '想在 {site} 切多個帳號跑 {flow},怎麼設計比較乾淨?' },
      { cat: 'question', t: '錄製器有沒有條件式 breakpoint?只想在某 value 出現時停下來。' },
      { cat: 'question', t: 'Workflow 檔放 git,有人做 PR review template 嗎?' },
      { cat: 'question', t: '{file} 200MB 以上,{module} 會不會直接 OOM?' },
      { cat: 'question', t: 'Webhook 入口的 signature 驗證,官方範例在哪?' },
      { cat: 'question', t: '請問 {module} 跑 {flow} 失敗時,可以 fallback 到別的 module 嗎?' },
      { cat: 'bug',      t: '上週還能跑的 {flow} 突然壞掉,Chromium 自動更新後就 {err}。' },
      { cat: 'bug',      t: '兩個 sub-workflow 並行跑,改到同一個變數,結果隨機哪個贏。' },
      { cat: 'bug',      t: '錄製器在開 DevTools 後失去焦點,要關掉 DevTools 才能繼續錄。' },
      { cat: 'bug',      t: '空的 {file} 餵給 {module} 直接 crash,不是回 empty array。' },
      { cat: 'feature',  t: '希望 step-level timeout,不要 workflow-level 一次設。' },
      { cat: 'feature',  t: '可以加 Telegram module 嗎?台灣很多公司用 Telegram 不用 Slack。' },
      { cat: 'feature',  t: '想要兩次 run log 的 diff 比對,看為什麼這次失敗那次成功。' },
      { cat: 'feature',  t: 'Conditional breakpoint — 條件成立才停下來。' },
      { cat: 'discussion', t: '我們公司把 18 支內部 script 收成 6 個 Flyto2 workflow,AMA。' },
      { cat: 'discussion', t: '故事時間:Flyto2 救了我們不用換掉用 12 年的舊 ERP。' },
      { cat: 'discussion', t: '視覺編輯器把複雜度藏起來,出問題就難 debug — JSON 為主比較好?' },
      { cat: 'discussion', t: '會計阿姨第一次看到 Flyto2 的反應你各位猜得到嗎?' },
      { cat: 'discussion', t: 'Open source 的話,什麼條件會讓你願意把內部 module 推上去?' },
    ],
    ja: [
      { cat: 'question', t: '{site} で {flow} を実行したいのですが、selector が安定しません。コツありますか?' },
      { cat: 'question', t: '{module} に {file} を渡すときの正しい形式を教えてください。' },
      { cat: 'question', t: 'Self-host で動かす場合、最低スペックはどのくらいでしょうか?' },
      { cat: 'question', t: '{flow} を {timing} で動かしていますが、{err} が出ます。対処法は?' },
      { cat: 'question', t: 'モバイル表示でレコードする際の注意点はありますか?' },
      { cat: 'question', t: 'CLI で {feature} を呼び出せますか?' },
      { cat: 'bug',      t: 'バグ:{site} で {module} が空配列を返す。DOM にはデータが見える。' },
      { cat: 'bug',      t: '{flow} 中に {err} が出てワークフロー全体が落ちる。' },
      { cat: 'bug',      t: 'Modal を閉じる動作が記録されない。' },
      { cat: 'feature',  t: '{site} 公式モジュールがほしいです。' },
      { cat: 'feature',  t: '{feature} の追加を希望します。' },
      { cat: 'discussion', t: '日本語ローカライズの精度について、皆さんどう感じていますか?' },
      { cat: 'discussion', t: '社内で {flow} を Flyto2 に置き換えたら工数が半分になりました。' },
      { cat: 'discussion', t: 'Zapier から移行を検討中。注意点があれば教えてください。' },
      // ---- expanded variety ----
      { cat: 'question', t: 'タイムゾーン問題:cron 表現は UTC ですか?それとも JST ですか?' },
      { cat: 'question', t: 'OAuth トークンが 24h で expire します。Flyto2 で自動 refresh する方法は?' },
      { cat: 'question', t: '{file} が 100MB 超えると {module} は問題なく動きますか?' },
      { cat: 'question', t: '複数アカウントの切り替えはワークフロー内でどう実装しますか?' },
      { cat: 'bug',      t: '長時間実行で OOM になります(4時間 / 5GB)。' },
      { cat: 'bug',      t: '空ファイルで {module} がクラッシュします。' },
      { cat: 'feature',  t: 'Step-level timeout が欲しいです(workflow-level だと粗すぎる)。' },
      { cat: 'feature',  t: 'Telegram モジュールの追加を希望します。' },
      { cat: 'discussion', t: '社内で 18 個のスクリプトを 6 ワークフローに集約した話。' },
      { cat: 'discussion', t: 'バレ、Flyto2 のおかげで 12 年物 ERP の刷新を見送れました。' },
    ],
  },
  code: {
    en: [
      { cat: 'question', t: 'How does Warroom reachability differ from {tool}?' },
      { cat: 'question', t: 'Can I write a custom rule for {finding}?' },
      { cat: 'question', t: 'Best way to integrate Warroom with {ci}?' },
      { cat: 'question', t: 'Does the closed-loop verifier handle {finding} on {repo}?' },
      { cat: 'question', t: 'Self-host: any {standard}-friendly air-gapped install path?' },
      { cat: 'question', t: 'For {standard} audit, which Warroom report do auditors usually accept?' },
      { cat: 'question', t: 'Pricing for Enterprise self-host with {standard} attestation?' },
      { cat: 'question', t: 'How do I exclude {finding} on test-only paths without disabling {rule} entirely?' },
      { cat: 'question', t: 'Webhook payload schema when score crosses threshold — documented?' },
      { cat: 'question', t: 'BYOK LLM — which models work best for AutoFix on {language}?' },
      { cat: 'question', t: 'Can the closed-loop verifier hit our staging behind a VPN?' },
      { cat: 'question', t: 'Is there a way to suppress {finding} but keep audit trail?' },
      { cat: 'question', t: 'CSPM coverage — does Warroom check {standard} CIS controls on AWS?' },
      { cat: 'bug',      t: 'False positive: {rule} fires on a known-safe pattern in {repo}.' },
      { cat: 'bug',      t: 'Scanner missed {finding} that {tool} caught.' },
      { cat: 'bug',      t: 'Indexer crash on {language} project with circular imports.' },
      { cat: 'bug',      t: '{rule} does not respect `.flyto-rules.yaml` overrides.' },
      { cat: 'bug',      t: 'CLI `flyto-index scan` chokes on a {repo} repo > 1M LOC.' },
      { cat: 'bug',      t: 'AutoFix PR modified yarn.lock without `--allow-lockfile`.' },
      { cat: 'bug',      t: 'Reachability returns "unreachable" for a function I can clearly call from {repo}.' },
      { cat: 'bug',      t: 'Secret scanner missed an AWS key that {tool} catches in the same commit.' },
      { cat: 'bug',      t: 'License scanner reports MIT for an actually-AGPL package on {language}.' },
      { cat: 'feature',  t: 'Support for {language} — is it on the roadmap?' },
      { cat: 'feature',  t: '{ide} extension for inline finding annotations?' },
      { cat: 'feature',  t: 'Bulk AutoFix PRs for {finding} across all our repos.' },
      { cat: 'feature',  t: 'EPSS-based prioritisation in the dashboard.' },
      { cat: 'feature',  t: 'Add Slack notification when score drops below B on {repo}.' },
      { cat: 'feature',  t: 'OWASP Top-10 mapping per finding so non-sec engineers can grok it.' },
      { cat: 'feature',  t: 'IaC scanning for Pulumi (we do not use Terraform).' },
      { cat: 'feature',  t: 'Per-team Bitsight-style score with diff over time.' },
      { cat: 'feature',  t: '{ide} inline AutoFix preview before applying.' },
      { cat: 'discussion', t: 'How are folks handling {finding} discovered in vendor SDK?' },
      { cat: 'discussion', t: 'When do you actually action a "C" health score? B?' },
      { cat: 'discussion', t: 'Comparing closed-loop verify vs traditional DAST — anyone done both?' },
      { cat: 'discussion', t: 'Pentest-as-code workflow for {finding} — share yours.' },
      { cat: 'discussion', t: 'False-positive rate honest take after 3 months: ours dropped from 40% to 7%.' },
      { cat: 'discussion', t: 'A-F score for execs: how do you communicate a B vs C to non-technical board?' },
      { cat: 'discussion', t: 'Anyone running Warroom on a 100k-LOC monorepo with submodules?' },
      // ---- expanded variety ----
      { cat: 'question', t: 'How does Warroom score weight {finding} severity vs reachability?' },
      { cat: 'question', t: 'Multi-tenant scenario: can we segment Warroom by client repo group?' },
      { cat: 'question', t: 'For incident response, can pentest YAML be triggered ad-hoc by SIEM webhook?' },
      { cat: 'question', t: 'API for ingesting third-party SAST results (we still pay for {tool} for one team).' },
      { cat: 'question', t: 'How long does the closed-loop verifier wait before marking unreachable?' },
      { cat: 'question', t: 'Single sign-on with our IdP — SAML or OIDC?' },
      { cat: 'question', t: 'Can audit findings be exported to Jira with field mapping?' },
      { cat: 'bug',      t: 'Pentest YAML keeps re-creating same issue every nightly run despite fix.' },
      { cat: 'bug',      t: 'AutoFix PR conflicts with our renovate-bot updates within minutes.' },
      { cat: 'bug',      t: 'Indexer scans .next/ build artifacts and flags React internals.' },
      { cat: 'bug',      t: 'Reachability times out on monorepo > 100 packages even with --low-mem.' },
      { cat: 'bug',      t: '`{rule}` fires on test fixtures despite glob_deny pattern.' },
      { cat: 'feature',  t: 'Allow customising the score weighting per workspace (security-critical vs internal tool).' },
      { cat: 'feature',  t: 'Diff view between two scans on same commit (e.g. before/after dep upgrade).' },
      { cat: 'feature',  t: 'Native GitLab MR comment integration like the GitHub action.' },
      { cat: 'feature',  t: 'Suppress finding only for one branch (e.g. accept on main, fix on next-major).' },
      { cat: 'discussion', t: 'Hot take: SAST is a maintenance burden if you do not act on findings within 7 days.' },
      { cat: 'discussion', t: 'Real talk on EPSS — is anyone weighting it heavily in their priority queue?' },
      { cat: 'discussion', t: 'Closed-loop verify on production is risky — discuss.' },
      { cat: 'discussion', t: 'How do you onboard a new repo without overwhelming the team with 200+ findings on day 1?' },
    ],
    zh: [
      { cat: 'question', t: '可以解釋一下 reachability 是怎麼算的嗎?跟 {tool} 不一樣。' },
      { cat: 'question', t: '怎麼把 Warroom 接到 {ci}?目前 PR review 是手動跑。' },
      { cat: 'question', t: '對 {standard} 合規,大家是直接信任 Warroom 報告還是另外做?' },
      { cat: 'question', t: '{sdlc} 階段就擋住 {finding} 是不是太晚?該往左移到 {ide} 嗎?' },
      { cat: 'question', t: 'API 怎麼用?想自架 daemon 把 finding 推到我們內部 ticketing。' },
      { cat: 'question', t: '誤判率高的話,{rule} 該怎麼降?' },
      { cat: 'question', t: 'Enterprise 報價怎麼算?我們是 monorepo,~50 個 service。' },
      { cat: 'bug',      t: '{rule} 在 {language} 專案誤判,issue 已經提了。' },
      { cat: 'bug',      t: 'Pentest YAML 對 {finding} 重跑不過,evidence pack 是空的。' },
      { cat: 'bug',      t: 'AutoFix PR 把不該動的 yarn.lock 改了,reviewer 全駁回。' },
      { cat: 'bug',      t: '{repo} repo 跑 scanner 卡住,記憶體爆掉。' },
      { cat: 'bug',      t: 'License scanner 把 AGPL 報成 MIT。' },
      { cat: 'feature',  t: '希望支援 {language} 的 SAST,我們半年後要全面換。' },
      { cat: 'feature',  t: '能不能在 dashboard 看 EPSS 分數一起排序?' },
      { cat: 'feature',  t: 'AutoFix dry-run + code review by AI 後再開 PR。' },
      { cat: 'feature',  t: '紅隊週會分享:用 Warroom 的 pentest YAML 重現 {finding},效率比手寫快很多。' },
      { cat: 'discussion', t: 'CTO 在問:Warroom 一個 score 比 {tool} 八個面板強在哪?' },
      { cat: 'discussion', t: '對比 Aikido 跟 Snyk,我們團隊跑了 3 個月的心得分享。' },
      { cat: 'discussion', t: '誤判率從 40% 降到 7%,整理了一下 .flyto-rules.yaml 的最佳實踐。' },
      { cat: 'discussion', t: '想討論:closed-loop verify 跟傳統 DAST 各自的適用場景。' },
      // ---- expanded variety ----
      { cat: 'question', t: '我們是 monorepo,500 個 service,scan 走得動嗎?有人實測過嗎?' },
      { cat: 'question', t: 'SSO 接 OIDC 還 SAML?我們 IdP 是 Auth0。' },
      { cat: 'question', t: 'Closed-loop verifier 跑 production 是不是太冒險?有人這麼幹嗎?' },
      { cat: 'question', t: '怎麼讓新接手的 repo 第一天不要冒出 200 個 finding 嚇到 dev?' },
      { cat: 'bug',      t: '已經修好的 {finding},Pentest YAML 每晚還是 re-create 同個 issue。' },
      { cat: 'bug',      t: 'AutoFix PR 跟 Renovate bot 幾分鐘內就衝突,合不進去。' },
      { cat: 'bug',      t: 'Indexer 把 `.next/` build artifact 當 source code,亂噴 React 內部 false positive。' },
      { cat: 'feature',  t: '希望可以對特定 branch 抑制 finding(main 接受、next-major 才修)。' },
      { cat: 'feature',  t: '兩次 scan 的 diff view,比如 dep upgrade 前後。' },
      { cat: 'discussion', t: 'Closed-loop 跑 production 各位怎麼看?要不要強制只能跑 staging?' },
      { cat: 'discussion', t: 'EPSS 各位真的有當主要排序依據嗎?還是只是參考?' },
      { cat: 'discussion', t: '紅隊週會分享:用 Warroom 的 pentest YAML 重現 OWASP Juice Shop 攻擊鏈,效率比手寫快 5 倍。' },
    ],
    ja: [
      { cat: 'question', t: '{ci} との連携手順を教えていただけますか?' },
      { cat: 'question', t: '{standard} 監査に提出できるエビデンス形式は?' },
      { cat: 'question', t: 'Reachability 解析のロジックを教えてください。{tool} と何が違うのか気になります。' },
      { cat: 'question', t: 'Self-host で {standard} に対応した air-gapped インストールは可能ですか?' },
      { cat: 'question', t: 'BYOK LLM はどのモデルが {language} の AutoFix に向いていますか?' },
      { cat: 'bug',      t: '{rule} が {language} プロジェクトで誤検知します。' },
      { cat: 'bug',      t: 'Indexer が大きい monorepo でクラッシュします。' },
      { cat: 'bug',      t: 'AutoFix PR が lockfile を意図せず変更しました。' },
      { cat: 'feature',  t: '{language} の SAST サポートを希望します。' },
      { cat: 'feature',  t: '{ide} 拡張で finding をインライン表示してほしいです。' },
      { cat: 'feature',  t: 'EPSS によるソートを dashboard に追加してください。' },
      { cat: 'discussion', t: 'Aikido から Warroom に乗り換えた所感を共有します。' },
      { cat: 'discussion', t: 'クローズドループ検証と従来の DAST、皆さんどう使い分けていますか?' },
      // ---- expanded variety ----
      { cat: 'question', t: '500 サービスのモノレポで scan 動きますか?実測例があれば。' },
      { cat: 'question', t: 'IdP 連携は SAML / OIDC どちらがおすすめですか?' },
      { cat: 'question', t: '新規 repo 接続時、初日に 200 件超の finding をどう dev に説明していますか?' },
      { cat: 'bug',      t: '修正済みの {finding} が毎晩の Pentest YAML 再実行でまた issue を作ってしまいます。' },
      { cat: 'bug',      t: 'AutoFix PR が Renovate bot のアップデートと数分でコンフリクトします。' },
      { cat: 'feature',  t: 'ブランチ単位での finding 抑制(main では許容、next-major で修正)を希望します。' },
      { cat: 'discussion', t: 'EPSS を主指標として採用している方、運用感を共有してください。' },
      { cat: 'discussion', t: 'Closed-loop verify を本番に向けるのはリスク高すぎ?staging 限定の運用が現実的では?' },
    ],
  },
};

// ============================================================
// Body padding sentences per (product, lang)
// ============================================================

export const BODY_PADDING = {
  cloud: {
    en: [
      'Tried it on macOS and Windows, same result.',
      "I checked the docs but couldn't find anything matching exactly.",
      'Happy to share the workflow file if it helps debug.',
      'This worked last week and started failing after the latest update.',
      'Already tried clearing cache + reinstalling Chromium.',
      'Workflow ID: cf-001 — happy to share read-only.',
      'For context: small team (4 people), all non-developers.',
      "We are evaluating Flyto2 vs commercial alternatives. This is a blocker.",
      'No rush, just curious if anyone has hit this before.',
      'Even running it headless gives the same error.',
      'I will keep digging on my end too — happy to PR if I find a fix.',
    ],
    zh: [
      '我們團隊每天會跑這個 workflow,所以蠻急的。',
      '希望能有 best practice 範例可以參考。',
      '目前的 workaround 是手動跑,但這違背了自動化的初衷。',
      '已經試過清 cache + 重裝 Chromium。',
      '對了,Pro 版本會解決嗎?還是兩個 tier 都同樣行為?',
      '附上 workflow 檔,需要的話可以丟過去。',
      '想等下個 release 看看,還是直接走 OSS 比較快?',
      '官方 docs 找了一下沒看到 — 可能是我關鍵字沒下對。',
    ],
    ja: [
      '社内で複数人がこの workflow を毎日動かしています。',
      'ベストプラクティス例があれば嬉しいです。',
      '現状は手動で回避していますが、自動化の意味がなくなります。',
      'docs はざっと見ましたが該当箇所が見つかりませんでした。',
      'Workflow ファイルは共有可能です。',
    ],
  },
  code: {
    en: [
      'Repo: ~50k LOC, polyglot.',
      'Snyk reports 12 highs on the same module — Warroom flags 3.',
      'CI run takes 14 minutes total, scan is ~3 min of that.',
      'Compliance team is asking for evidence — what is the recommended export?',
      "I'll attach the offending file once I sanitise it.",
      'Reachability seems off here — there is clearly a path through the controller.',
      'If this is a docs issue, happy to PR.',
      'Currently using {tool}, considering migration but worried about regression.',
    ],
    zh: [
      '我們是 monorepo,500 個 service 共一個 repo,scan 走得動嗎?',
      '希望可以加上 EPSS 排序,critical 太多看不完。',
      '0.5 升 0.6 後,count 從 40 降到 14,規則有改嗎?',
      '紅隊週會剛好提到這個,做完 closed-loop verify 比想像中順。',
      '有規劃支援 SBOM (CycloneDX) 嗎?audit 要交。',
    ],
    ja: [
      '社内 monorepo で 200k LOC 規模です。',
      'コンプライアンス対応のため、エビデンス出力形式を確認したいです。',
      'CI 実行時間は全体 14 分、scan は約 3 分です。',
      'もし docs の問題なら PR を送ります。',
    ],
  },
};

// ============================================================
// Admin reply templates per (product, lang)
// ============================================================

export const ADMIN_REPLIES = {
  cloud: {
    en: [
      'Good find — this is a known edge case with {site}. Workaround: switch the recorder to "stable selectors" mode (Settings → Recorder → Stable Mode). We are shipping a proper fix in 3.x.',
      'Thanks for the report. Can you share the workflow file? Easier to reproduce that way.',
      'This is by design right now: {module} only runs on the active tab. We are evaluating multi-tab support — tracked in #4421.',
      'Yep, {feature} is on the Q3 roadmap. Will land alongside the new visual editor.',
      'Quick fix: add `wait_for_selector` with a 10s timeout before the action. The page is async on first load.',
      'You can do this with `flow.foreach` over the rows + `sheets.append` per iteration. Example workflow attached.',
      'Pricing is per-point, not per-task. {flow} typically uses ~50 points/run.',
      'Your data stays on your machine. The cloud is opt-in for scheduling and team sharing.',
      'Try the latest desktop build (3.4.2). We rewrote the recorder for {site}-style sites in this release.',
      'Closing as duplicate of #2871. Subscribe there for updates.',
      'Self-hosting: Docker image is `flytohub/flyto2:latest`. Just outbound HTTPS, no public IP needed.',
      'Recorder does not bypass CAPTCHA on purpose. We pause and prompt you to solve it manually, then continue.',
      'Could you open this on GitHub? Easier to track for the engineering team: github.com/flytohub/flyto2/issues',
      'Will follow up here once 3.5 ships (mid-May). Workaround until then: pin Chromium with `flyto2 chromium pin 130`.',
      'Thanks — assigning to engineering. Will post here when fixed. Track via #5217.',
    ],
    zh: [
      '感謝回報,這個應該是 selector 抓不穩的問題。下版會切到 semantic mode,週五出。',
      '可以的,在 Settings → Workflow → Variables 那邊加 scope=run 就會跨 sub-workflow 共享。',
      '理解你的痛點 — 我們也常遇到。預計下個 release 把 {feature} 加進來,直接寫到 Sheets。',
      '請看一下 docs.flyto2.com/recipes 那邊的 {flow} 範例,九成情況可以直接套用。',
      '這個 case 你說得對,我們現在記下來,Tracker 編號 #5102,subscribe 之後通知。',
      'Cloud 跑在你機器上,憑證不會離開磁碟。如果想 audit,看 `~/.flyto2/audit.jsonl`,每行 HMAC 簽章。',
      '最快的解法是用 `recipe site-audit` 一次抓完,輸出 JSON 後再用 {module} 篩。',
      '對,目前這個是限制。Workaround:把 modal 拆成獨立的 sub-workflow,parent 用 wait_for 等 modal close。',
      '你說的這個其實已經在 nightly。下載 nightly 試試,或等 stable 月底前釋出。',
      '不好意思讓你花了時間。下個 patch 會修。中間先用 retry 3 次搭 backoff 緩衝。',
    ],
    ja: [
      'ご報告ありがとうございます。次回リリースで semantic selector モードに切り替えます。',
      '`flow.foreach` と `sheets.append` の組み合わせで対応できます。サンプル workflow を共有しますね。',
      '{feature} は次の release で対応予定です。発表したらこちらでお知らせします。',
      'docs に追記しました — docs.flyto2.com/recipes を参照ください。',
      '記録としてエンジニアリングチームに共有しました。Tracker: #5102。',
      'Cloud は端末上で動作します。認証情報はディスクから出ません。',
      'バグ確認しました。次のパッチで修正、当面は retry を 3 回設定してください。',
    ],
  },
  code: {
    en: [
      'Closed-loop verifier got it. The {finding} is `exploitable` — evidence pack attached. Replaying nightly.',
      'You are right, that rule is too aggressive. Tightening the regex in next release of `flyto-indexer`.',
      'Reachability for {finding} requires the function call graph. Make sure you ran `flyto-index scan --deep`.',
      'For {standard} audit, the SOC 2 evidence bundle exports as PDF + JSON. See `flyto2 export soc2`.',
      'Self-host with air-gapped install: contact info@flyto2.com for the offline license + signed bundle.',
      'AutoFix PR was conservative on purpose — yarn.lock changes are gated behind a separate flag. Pass `--allow-lockfile`.',
      'Yes, {language} support is being added in Phase III. Tracking issue: github.com/flytohub/flyto-code/issues/142.',
      'EPSS sorting lands in 0.7. Until then, you can sort the JSON export by `epss_score` field.',
      'CLI: `flyto-index audit` is what you want. The web UI is read-only on top of the same index.',
      'False-positive in {rule}? Add a `.flyto-rules.yaml` override with `glob_deny` for the path.',
      'For {ci}, use the official action: `flytohub/scan-action@v1`. Reads PR diff, posts comments inline.',
      'For Enterprise pricing, send a note to info@flyto2.com — we tier by repo count + LOC.',
      'Custom SAST rules use the same syntax as Semgrep. We have an examples repo: github.com/flytohub/warroom-rules.',
      'Indexer for 1M LOC repo: memory peak ~3GB. If your machine < 8GB, add `--low-mem` flag.',
    ],
    zh: [
      '感謝回報。確認是 false positive,下個版本 {rule} 加白名單。',
      '請用 reachability mode 跑一次 — 如果結果是 "unreachable",可以暫時降優先級。',
      '我們有跟 {standard} 的審計師對過,Warroom 的 evidence pack 直接過。',
      '可以,closed-loop verifier 走 staging tunnel,VPN 後面也跑得到。',
      'AutoFix 預設保守是因為 lockfile 影響大。`--aggressive` 可以打開。',
      '{language} SAST 規則是社群提的 — github.com/flytohub/flyto-indexer/pulls,歡迎 PR。',
      'OWASP mapping 在 dashboard 的 finding 詳情頁,展開就有。0.7 加排序。',
      '誤判率高的話,先看 `.flyto-rules.yaml` 有沒有設好。',
      'CSPM 對 AWS CIS 1.5 全 control 都有,GCP / Azure 在 Phase IV。',
      '感謝你的紅隊報告,加進 regression vault 每晚對 demo 環境重跑。',
    ],
    ja: [
      'ご報告ありがとうございます。誤検知として確認しました、次のリリースで {rule} に whitelist を追加します。',
      'Reachability mode で再実行してください。`unreachable` なら優先度を下げて構いません。',
      '{standard} 監査用の evidence bundle は `flyto2 export soc2` で出力できます。',
      'Self-host について info@flyto2.com にご連絡ください。オフラインライセンスをお送りします。',
      '{language} SAST は Phase III で対応予定です。Issue #142 で追跡できます。',
      'AutoFix の lockfile 変更は `--allow-lockfile` フラグで明示的に有効化が必要です。',
    ],
  },
};

export const COMMUNITY_REPLIES = {
  cloud: {
    en: [
      'Same here on Linux. Let me know if you find a fix.',
      'I hit this last week — turns out you need to set `headless=false` for that site.',
      '+1, also blocked. Subscribing.',
      'Have you tried the `wait_for_dom` module before this step?',
      'Same problem on a Korean vendor portal. Workaround: switched to API mode (their hidden API works fine).',
      'Could you share your workflow file? Curious to compare with mine.',
      'I run a similar flow daily without issues. Maybe a timing thing — try adding a 500ms delay.',
      'Following — would love a working example for this.',
    ],
    zh: [
      '可以試試把 Chromium 降到 130,我之前是這樣繞過的。',
      '+1 我也卡這個,訂閱看後續。',
      '同問,有解的話請更新一下。',
      '感謝分享!最近也在做類似的 work flow。',
      '我這邊跑都正常欸,你 macOS 版本是?',
    ],
    ja: [
      'こちらでも同じ症状です。',
      '`wait_for` を入れたら解決しました、お試しを。',
      '+1、解決策があれば共有お願いします。',
    ],
  },
  code: {
    en: [
      'Saw the same FP on our side. Suppression rule worked.',
      'Reachability flagged it as unreachable for us — maybe enable `--include-tests` if your call comes from a test harness.',
      'We hit the same with Snyk. Warroom closed-loop confirmed it was sanitized at the framework level.',
      'Aikido caught this for us too but Warroom evidence pack was way more useful.',
      'Worth filing as a bug — sounds like a rule edge case.',
    ],
    zh: [
      '我們是把這條規則 disable,然後寫 custom 的 grep_deny。',
      '同問,Aikido 也誤判,期待修復。',
      '+1,希望可以修。',
    ],
    ja: [
      '弊社でも同じ誤検知が出ます。',
      'Suppression rule で対応しました、参考まで。',
    ],
  },
};

// ============================================================
// Tags per (product, category) — language-agnostic
// ============================================================

export const TAGS = {
  cloud: {
    question:   ['howto', 'recorder', 'selectors', 'recipes', 'sheets', 'auth', 'mac', 'windows', 'cli'],
    bug:        ['repro', 'flake', 'timeout', 'memory', 'crash', 'macos', 'windows', 'iframe', 'shadow-dom'],
    feature:    ['recorder', 'editor', 'modules', 'cli', 'mobile', 'export', 'docs'],
    discussion: ['ops', 'security', 'pricing', 'comparison', 'best-practice', 'community'],
  },
  code: {
    question:   ['sca', 'sast', 'reachability', 'closed-loop', 'cli', 'ci', 'config'],
    bug:        ['false-positive', 'crash', 'cli', 'rule', 'autofix'],
    feature:    ['language-support', 'ide', 'autofix', 'epss', 'iac', 'cspm'],
    discussion: ['compliance', 'comparison', 'red-team', 'methodology', 'pricing'],
  },
};
