/**
 * One-shot forum moderation pass — DESTRUCTIVE.
 *
 * Scans every forum_posts document and asks Claude to classify each one.
 * Posts flagged as anything other than "safe" are RECURSIVELY DELETED
 * (post + its comments subcollection + its reactions subcollection) when
 * run with --apply.
 *
 * Usage:
 *   # one-time install (won't pollute package.json):
 *   npm install --no-save firebase-admin @anthropic-ai/sdk
 *
 *   # dry-run (default — no deletes, prints summary + samples):
 *   GOOGLE_APPLICATION_CREDENTIALS=./.firebase-sa.json \
 *     ANTHROPIC_API_KEY=sk-ant-... \
 *     node scripts/moderate-once.mjs
 *
 *   # actually delete:
 *   ... node scripts/moderate-once.mjs --apply
 *
 *   # only scan first N (debug):
 *   ... node scripts/moderate-once.mjs --limit 200
 *
 *   # NUKE — wipe the entire forum_posts collection, skip LLM entirely.
 *   # dry-run first (no --apply):
 *   ... node scripts/moderate-once.mjs --nuke
 *   # really do it:
 *   ... node scripts/moderate-once.mjs --nuke --apply
 */

import { initializeApp, cert, applicationDefault } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
import Anthropic from '@anthropic-ai/sdk';
import { readFileSync, existsSync, writeFileSync } from 'node:fs';

const argv = process.argv.slice(2);
const APPLY = argv.includes('--apply');
const NUKE = argv.includes('--nuke');
const LIMIT_IDX = argv.indexOf('--limit');
const LIMIT = LIMIT_IDX > -1 ? Number(argv[LIMIT_IDX + 1]) : 0;

const BATCH_SIZE = 20;
const CONCURRENCY = 4;
const MODEL = 'claude-sonnet-4-6';

// ----------------------------------------------------------------
// Init
// ----------------------------------------------------------------

const saPath = process.env.GOOGLE_APPLICATION_CREDENTIALS;
if (saPath && existsSync(saPath)) {
  initializeApp({ credential: cert(JSON.parse(readFileSync(saPath, 'utf8'))) });
} else {
  initializeApp({ credential: applicationDefault() });
}
const db = getFirestore();

// LLM only needed when classifying. --nuke skips it entirely.
let anthropic = null;
if (!NUKE) {
  if (!process.env.ANTHROPIC_API_KEY) {
    console.error('ANTHROPIC_API_KEY not set (required unless --nuke).');
    process.exit(1);
  }
  anthropic = new Anthropic();
}

// ----------------------------------------------------------------
// Classifier prompt
// ----------------------------------------------------------------

const SYSTEM = `You are a content-moderation classifier for the Flyto2 forum
— a browser-automation product Q&A board, mixed en/zh/ja content.

For each post, decide whether it should remain on the public board. Posts
you flag will be PERMANENTLY DELETED (along with their comments and
reactions). Err on the side of deletion: this corpus was seeded by an
LLM script and we are scrubbing it down to genuinely usable posts.

DELETE if the post asks about, promotes, or provides instructions for:

- Banking / financial credential automation, 2FA/OTP bypass, intercepting
  SMS verification codes, automating bank logins, wire transfers,
  brokerage / crypto-exchange logins. Even "I want to auto-login to my
  bank to check balance" counts — the public board should not surface it.
- Scams, phishing, account farming, fake reviews, account selling,
  identity forgery, money laundering.
- Scalping bots: tickets, sneakers, limited drops, queue jumping. Flyto2
  has scalper users but we don't surface this help publicly.
- NSFW / adult / sexual / escort / dating-scam content.
- Violence, weapons, drugs, self-harm, suicide instructions.
- Hate speech, racial / ethnic / gender slurs.
- Workplace objectification — referring to coworkers via infantilizing or
  aging labels: "會計阿姨", "財務妹妹", "OL girl", "前台妹妹", anything
  that pairs a job title with a gendered diminutive. The compound is the
  problem; the standalone word may be neutral.
- Geopolitical flashpoints — Taiwan/HK/Tibet/Xinjiang independence,
  Tiananmen / Cultural Revolution discussion, Japanese WWII revisionism,
  Israel/Palestine — off-topic for a browser-automation forum.
- Pure spam, low-effort noise (one-line nothing, all-emoji, near-duplicates).
- Template/seed artifacts: title verbatim re-pasted inside the body,
  glued-on non-sequiturs ("已經試過清 cache + 重裝 Chromium"
  appearing irrelevantly at the end), identical voice/cadence across many
  posts. These were generated by the old seed script and should be culled.

KEEP if the post is a normal user question about browser automation,
recording workflows, scraping public data, integrating with mainstream
SaaS (Gmail, Slack, Google Sheets, internal dashboards, e-commerce
catalogs, etc.) — even if grammar is rough or it reads ESL.

Reply with ONLY a JSON array, one element per post, in the same order as
input. No prose, no markdown fences. The "hidden" field means "should be
deleted":

[
  {"id": "<post id>", "hidden": true, "category": "banking_credentials",
   "reason": "asks how to bypass bank 2FA"},
  {"id": "<post id>", "hidden": false, "category": "safe", "reason": ""}
]

Allowed categories: safe, banking_credentials, fraud, scalping, nsfw,
violence, hate, workplace_objectification, political, spam,
template_artifact, other.`;

async function classifyBatch(batch) {
  const userMsg = batch
    .map((p, i) =>
      [
        `# Post ${i + 1}`,
        `id: ${p.id}`,
        `lang: ${p.lang}`,
        `title: ${p.title}`,
        `body: ${(p.body || '').slice(0, 800)}`,
      ].join('\n'),
    )
    .join('\n\n---\n\n');

  const resp = await anthropic.messages.create({
    model: MODEL,
    max_tokens: 4000,
    system: [
      { type: 'text', text: SYSTEM, cache_control: { type: 'ephemeral' } },
    ],
    messages: [{ role: 'user', content: userMsg }],
  });

  const text = resp.content
    .filter((b) => b.type === 'text')
    .map((b) => b.text)
    .join('')
    .trim();

  // Strip ```json ... ``` fences if Claude added any.
  const cleaned = text
    .replace(/^```(?:json)?\s*/i, '')
    .replace(/```\s*$/i, '')
    .trim();

  try {
    return JSON.parse(cleaned);
  } catch (err) {
    console.error('\nFailed to parse classifier output:');
    console.error(cleaned.slice(0, 500));
    throw err;
  }
}

// ----------------------------------------------------------------
// Main
// ----------------------------------------------------------------

async function nukeMain() {
  console.log(`Mode: ${APPLY ? 'NUKE + APPLY — wiping forum_posts collection' : 'NUKE DRY-RUN — no deletes'}`);
  console.log('');

  const snap = await db.collection('forum_posts').get();
  console.log(`forum_posts contains ${snap.size} documents.`);

  // Tally subcollections we'll lose too, for transparency.
  let comments = 0;
  let reactions = 0;
  await Promise.all(
    snap.docs.map(async (d) => {
      const [c, r] = await Promise.all([
        d.ref.collection('comments').count().get(),
        d.ref.collection('reactions').count().get(),
      ]);
      comments += c.data().count;
      reactions += r.data().count;
    }),
  );
  console.log(`  + ${comments} comments`);
  console.log(`  + ${reactions} reactions`);
  console.log('');

  if (!APPLY) {
    console.log('Dry-run only. Re-run with --nuke --apply to PERMANENTLY DELETE everything above.');
    return;
  }

  console.log('Nuking…');
  await db.recursiveDelete(db.collection('forum_posts'));
  console.log(`Done. forum_posts is now empty.`);
}

async function main() {
  if (NUKE) return nukeMain();

  console.log(`Mode:        ${APPLY ? 'APPLY (DELETES from Firestore — irreversible)' : 'DRY-RUN (no deletes)'}`);
  console.log(`Batch size:  ${BATCH_SIZE}`);
  console.log(`Concurrency: ${CONCURRENCY}`);
  console.log(`Model:       ${MODEL}`);
  if (LIMIT) console.log(`Limit:       ${LIMIT}`);
  console.log('');

  let q = db.collection('forum_posts').orderBy('created_at');
  if (LIMIT) q = q.limit(LIMIT);
  const snap = await q.get();

  const all = snap.docs.map((d) => ({ id: d.id, ...d.data() }));

  console.log(`Loaded ${snap.size} posts; classifying all of them.`);

  const batches = [];
  for (let i = 0; i < all.length; i += BATCH_SIZE) {
    batches.push(all.slice(i, i + BATCH_SIZE));
  }
  console.log(`→ ${batches.length} batches\n`);

  const stats = { scanned: 0, doomed: 0, byCategory: {}, byLang: {} };
  const samples = [];
  const flagged = []; // full list of every classification flagged for deletion

  let idx = 0;
  async function worker() {
    while (idx < batches.length) {
      const myIdx = idx++;
      const batch = batches[myIdx];
      try {
        const results = await classifyBatch(batch);
        for (const r of results) {
          stats.scanned++;
          if (!r.hidden) continue;
          stats.doomed++;
          stats.byCategory[r.category] = (stats.byCategory[r.category] ?? 0) + 1;
          const post = batch.find((p) => p.id === r.id);
          if (post) {
            stats.byLang[post.lang] = (stats.byLang[post.lang] ?? 0) + 1;
            flagged.push({
              id: r.id,
              lang: post.lang,
              product: post.product,
              category: r.category,
              reason: r.reason,
              title: post.title,
            });
            if (samples.length < 30) {
              samples.push({
                id: r.id,
                lang: post.lang,
                category: r.category,
                reason: r.reason,
                title: post.title,
              });
            }
          }
          if (APPLY) {
            // Recursive delete — post doc + comments subcollection +
            // reactions subcollection. Firestore subcollections don't
            // cascade on parent delete.
            await db.recursiveDelete(db.collection('forum_posts').doc(r.id));
          }
        }
        const pct = (((myIdx + 1) / batches.length) * 100).toFixed(1);
        const verb = APPLY ? 'deleted' : 'would-delete';
        process.stdout.write(
          `\rBatch ${myIdx + 1}/${batches.length} (${pct}%) — ${verb} so far: ${stats.doomed}    `,
        );
      } catch (err) {
        console.error(`\nBatch ${myIdx} failed:`, err.message);
      }
    }
  }

  await Promise.all(Array.from({ length: CONCURRENCY }, worker));

  console.log('\n\n=== Summary ===');
  console.log(`Scanned: ${stats.scanned}`);
  const pct = stats.scanned ? ((stats.doomed / stats.scanned) * 100).toFixed(1) : '0.0';
  console.log(`${APPLY ? 'Deleted' : 'Would-delete'}: ${stats.doomed} (${pct}%)`);

  console.log('\nBy category:');
  for (const [k, v] of Object.entries(stats.byCategory).sort((a, b) => b[1] - a[1])) {
    console.log(`  ${k.padEnd(22)} ${v}`);
  }

  console.log('\nBy language:');
  for (const [k, v] of Object.entries(stats.byLang).sort((a, b) => b[1] - a[1])) {
    console.log(`  ${k.padEnd(4)} ${v}`);
  }

  console.log(`\nSample (first 30 of ${APPLY ? 'deleted' : 'would-delete'}):`);
  for (const s of samples) {
    const t = (s.title || '').replace(/\s+/g, ' ').slice(0, 70);
    console.log(`  [${s.lang}] ${s.category.padEnd(24)} ${t}`);
    console.log(`         ↳ ${s.reason}`);
  }

  // Write the full flagged list for review, regardless of mode.
  // In dry-run this is your "what would happen" report.
  // In apply mode this is your audit log of what got deleted.
  const out = APPLY ? 'moderation-applied.json' : 'moderation-dryrun.json';
  writeFileSync(out, JSON.stringify(flagged, null, 2));
  console.log(`\nFull list: ./${out} (${flagged.length} entries)`);

  if (!APPLY) {
    console.log('\nDry-run complete. Re-run with --apply to DELETE flagged posts.');
  } else {
    console.log('\nDeleted. Reload the forum to confirm.');
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
